### ISSUE TITLE
[Mechanics] - Omniwheel roller extrusions should not cover the whole wheel

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kurgimopeed#16]
The extruded part locating the rollers should not touch anything but the internal part of the bearing. You would need to make a cut (red) and everything after that should be flat and further away from the rollers (blue)

![image](https://user-images.githubusercontent.com/5435954/139488523-d8fb2507-d7af-43b0-ac83-0ce771a9a27a.png)

Otherwise you can also use a conical extrusion similar to this:
![image](https://user-images.githubusercontent.com/5435954/139488659-8ecae026-55b8-4e30-82ca-79bff38fe179.png)

**Comment by Akustav** [comment]
Reopening. I would also remove these parts. They can touch the moving part of the bearing. 
![image](https://user-images.githubusercontent.com/5435954/140618980-b5eaca1c-facd-4e40-bfbe-21fedebca881.png)

**Comment by MattiasAvi** [comment]
Fixed This issue
