### ISSUE TITLE
[Mechanics] - camera should point a little more down.

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kurgimopeed#34]
You would want an angle more like this:

![image](https://user-images.githubusercontent.com/5435954/145786689-0c10049f-790a-40d3-b768-dc05801bc69f.png)

The advantage here is that you see the ball until the last possible moment. Additionally you do not see spectators and whatever noise might come from there.

**Comment by MattiasAvi** [comment]
Redesigned entire camera stand.
