### ISSUE TITLE
[Mechanics] - thrower angle adjust could use previous iteration

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kurgimopeed#35]
I would change the thrower angle-adjust a little. I would make it so that the movement of the internal ramp is guided by a separate arm that extends from the center of the ramp (also the center of the motor), like this:

![image](https://user-images.githubusercontent.com/5435954/145787315-49e83d43-6623-4775-9c2e-865eee4c4952.png)

Such a system allows for a very smoothly moving internal ramp. Do you have a motor with a shaft?

Additionally the simplest angle adjust would be something like this:
![image](https://user-images.githubusercontent.com/5435954/145787511-a1696f2f-6314-4482-8f7c-353dae1aa184.png)

Where the blue piece has a slot in it that goes into a pin that is attached to the moving ramp. If you move the servo up-down then the pin slides in this slot and allows the ramp to move either up or down.

**Comment by Akustav** [comment]
You can also look at how the servo arm was used in conjunction with the blue piece.

**Comment by Akustav** [comment]
Additionally it is unclear how stuff attaches to the servo since the servo horn is not in the model.

![image](https://user-images.githubusercontent.com/5435954/146066569-f485510a-9e2c-4e2f-8d5c-cc216fdefba0.png)

**Comment by Akustav** [comment]
I would also beef up the arm. It should bend as little as possible while throwing:

![image](https://user-images.githubusercontent.com/5435954/146967289-bb981863-25d2-4234-99e4-f7615cc36c67.png)

**Comment by MattiasAvi** [comment]
Made this part bulkier.

**Comment by Akustav** [comment]
How do you plan to assemble it? I would make it so that you fasten the arm to the servo horn and then screw this assembly to the servo. Currently you need to do the final assembly with the servo attached that can make it more difficult.

I would have a central hole in the arm that lets you attach and remove the assembly simply.

**Comment by MattiasAvi** [comment]
Thanks for this suggestion. It would have been quite annoying to assemble it. Made a hole in the center.
