### ISSUE TITLE
[Mechanics] - move thrower into the robot

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kurgimopeed#36]
Currently the thower allows to pull a ball in from quite far off the sides:

![image](https://user-images.githubusercontent.com/5435954/145788146-eb40e1be-5c2d-41a8-849c-904053d39772.png)

This can create an issue with accuracy since it can be pulled through the thrower at an angle (red arrow).

You can do multiple things to mitigate it:
* move thrower inside so the sidewalls guide and center the ball
* Have a tight front end with a grabbing mechanism that centers the ball
* Have a slimmer front-end overall and hope programmers to a good job

**Comment by MattiasAvi** [comment]
Moved robot thrower into the robot. Can't move any more because then PCB won't fit.
