### ISSUE TITLE
[Mechanics] - how are internal ramp components attached?

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kurgimopeed#37]
How are these pieces attached to eachother?

![image](https://user-images.githubusercontent.com/5435954/145788576-1a7f55ad-c057-4c36-91f6-ff1ed78dea5c.png)

**Comment by MattiasAvi** [comment]
Stationary parts are attached with bolts and spacers. Do we have any long rods at least 65 mm of length in Delta? Preferably around 3 mm diameter.

**Comment by Akustav** [comment]
I dont think we have such a rod. Why not use spacers instead? Would make assembly simpler and more robust. Additionally, why have the slot instead of 2 holes?

![image](https://user-images.githubusercontent.com/5435954/146065364-5fa73410-ffbd-4207-972c-879b8f458cd6.png)

**Comment by MattiasAvi** [comment]
I am going to use hex standoffs for spacing. Most spaces are multiples of 5.

**Comment by Akustav** [comment]
OK
