### ISSUE TITLE
[Mechanics] - button and power lead input out of spec

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kurgimopeed#38]
The power input for the computer and the switch ports are out of spec:

![image](https://user-images.githubusercontent.com/5435954/145788806-28e85695-a359-4c57-8f8d-0d650f88117d.png)

Their requirements can be found here: https://digilabor.ut.ee/index.php/Basketball_robot_mechanics_design#PC_power_adapter_socket

Additionally, your camera mount blocks the hole to the power socket.

**Comment by MattiasAvi** [comment]
Switch and button holes should fit specifications. Left some room at shorter ends of switch to fit it in better.

**Comment by Akustav** [comment]
You left space here? The Length is 32 mm
![image](https://user-images.githubusercontent.com/5435954/146065579-312ac75b-0ce4-4df7-9a18-21571e99fc2e.png)
