### ISSUE TITLE
[Mechanics] - what is the purpose of additional motor supports

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kurgimopeed#39]
What is the purpose of these components?

![image](https://user-images.githubusercontent.com/5435954/145789115-645d7553-a17e-4151-8229-79dabe18bd51.png)

They can make assembly/disassembly difficult. How are these components attached to each other, i see a hole for both of them, is this used?

**Comment by MattiasAvi** [comment]
Removed additional motor supports.
