### ISSUE TITLE
[Mechanics] - no batteries on model

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kurgimopeed#40]
Power delivery components missing:
* Batteries
* Battery mounting mechanism
* Power cables from Batteries
* Cable holes for other components, like camera, mainboard

**Comment by MattiasAvi** [comment]
Batteries are now on the robot and are attached with hook and loop fasteners.

**Comment by Akustav** [comment]
Just a note, I think you attached the batteries bottom side up.
