### ISSUE TITLE
[Mechanics] - RGB sensor of camera not in middle of robot

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kurgimopeed#41]
Is this designed as intended? Usually this makes programming more difficult since you now need to perspective correct the aim of the robot.

![image](https://user-images.githubusercontent.com/5435954/145789819-d544d9d8-4895-425f-9ce9-60b4ac1f8373.png)

**Comment by MattiasAvi** [comment]
Moved RGB sensor to the middle.

**Comment by Akustav** [comment]
The FOV cone is currently not attached to the RGB sensor, FYI:

![image](https://user-images.githubusercontent.com/5435954/146066035-c08355ea-595e-48be-89aa-6ad402e13aaf.png)

**Comment by MattiasAvi** [comment]
Changed the origin of FOV to RGB camera
