### ISSUE TITLE
[Mechanics] - roller design questions

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kurgimopeed#43]
Why is the roller asymmetrical? Based on my experience it has no big benefit compared to a normal round one since the ball has a rubbery texture and will stick to most surfaces.

I would suggest something similar to this:

![image](https://user-images.githubusercontent.com/5435954/146067428-4d11a239-d426-42e1-b4ae-4ef7cb0caa5b.png)
![image](https://user-images.githubusercontent.com/5435954/146067457-e0ad4b8d-5fea-4dda-95d5-47a8b34722a6.png)

This has the advantage of being simple to attach and remove, the servo horn should not be too much in the way. Additionally I would suggest making the whole roller girthier, to increase its strength. You might ram things with it.

**Comment by MattiasAvi** [comment]
I found asymmetrical design from one of the thrower design examples. But your idea seems much better and I made something similar.

**Comment by Akustav** [comment]
It is true that I have experimented with the asymmetrical design. It did not bring any tangible benefits compared to a round and symmetrical design.
