### ISSUE TITLE
[Mechanics] - no fasteners on the thower

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kurgimopeed#45]
I think you should add some fastening holes for the thrower into the bottom plate:

![image](https://user-images.githubusercontent.com/5435954/146967701-77b58287-a86c-4e57-99fd-41747d1dff67.png)

**Comment by MattiasAvi** [comment]
Added 4 holes to fasten the thrower. Is it enough or should I find a way to fasten thrower to upper plate also_

**Comment by Akustav** [comment]
I think it is fine
