### ISSUE TITLE
[Mechanics] - electronics board interference with motor encoder caps

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kurgimopeed#46]
The encoder caps and the electronics board intersect:

![image](https://user-images.githubusercontent.com/5435954/146967988-abb9a854-878a-4509-9adc-ff586cda0704.png)

**Comment by MattiasAvi** [comment]
Draw more precise PCB shape and now there\s no interference.

**Comment by Akustav** [comment]
I think you can not place the board on the bottom flat since it has headers that go through the board. Also if it lifts this might be an issue:
![image](https://user-images.githubusercontent.com/5435954/146980889-8a867ebf-289f-4c24-b0e7-166e55f562d6.png)

**Comment by MattiasAvi** [comment]
This should not be an issue because our robot's encoders are stripped from the case and in reality are quite smaller.

**Comment by Akustav** [comment]
If you say so
