### ISSUE TITLE
[Mechanics] - Some tabs need to be manually placed

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kurgimopeed#47]
Some internal contours are not held in place by just one tab:

![image](https://user-images.githubusercontent.com/5435954/147581557-dd0d9a76-513f-4f67-a3a5-5ac1a0b48103.png)

To fix this I would make a separate procedure for them with manually placed tabs.

**Comment by MattiasAvi** [comment]
Added more tabs to critical places.
