### ISSUE TITLE
[Mechanics] - weird order of operations

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kurgimopeed#48]
Why is the last operation a slot? It might rip the piece off the substrate since it is held on just by tabs:

![image](https://user-images.githubusercontent.com/5435954/147581690-a01bfeea-45ea-4626-b987-dd9296522f52.png)

**Comment by Akustav** [comment]
Similar issue is with the 2DContour2, where too much is in one operation. It might mille the OD out first, then does the internal slot, that might break off:

![image](https://user-images.githubusercontent.com/5435954/147581790-98022aee-f083-4a12-b384-50d1d45de184.png)

**Comment by MattiasAvi** [comment]
> Why is the last operation a slot? It might rip the piece off the substrate since it is held on just by tabs:
> 
> ![image](https://user-images.githubusercontent.com/5435954/147581690-a01bfeea-45ea-4626-b987-dd9296522f52.png)

My bad. Forgot to move it up. Managed to merge this contour with another and use 3 mm mill.

**Comment by MattiasAvi** [comment]
> Similar issue is with the 2DContour2, where too much is in one operation. It might mille the OD out first, then does the internal slot, that might break off:
> 
> ![image](https://user-images.githubusercontent.com/5435954/147581790-98022aee-f083-4a12-b384-50d1d45de184.png)

By changing some parameters I was able to get rid of the center slot. Now there are no tabs needed.
