### ISSUE TITLE
[Mechanics] - remove stock to leave

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kurgimopeed#50]
You currently set the stock to leave property in some of the operations. This has a side effect of things not fitting together since slots, for example, are 0.2mm tighter:

![image](https://user-images.githubusercontent.com/5435954/147687538-397707cb-6278-4d0b-89b7-bab4a0d1e1aa.png)

**Comment by Akustav** [comment]
This might re-create the unneeded tab issue.

**Comment by MattiasAvi** [comment]
Removed "Stock to leave" in tight spaces. Some warnings reappeared but shouldn't be a problem.
