### ISSUE TITLE
[Mechanics] - issue with stock size

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr21-team-kurgimopeed#51]
Currently you have 2 components that are 5 mm instead of 4.8mm. To minimize changes i would suggest changing the top offset to -0.2 mm:

![image](https://user-images.githubusercontent.com/5435954/147687782-c109a25a-06e3-4106-9157-68251a2ac9e4.png)

**Comment by MattiasAvi** [comment]
Changed width of those details and issue is fixed.
